add_compile_options(-O0 -g)

#cifuzz:build-template:begin
#add_fuzz_test({{ .FuzzTestName }} {{ .FileName }})
#target_link_libraries({{ .FuzzTestName }} PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,Threads::Threads>" PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,csp>")
#cifuzz:build-template:end
#add_fuzz_test(fuzz_csp_route_work fuzz_csp_route_work.cpp)
#target_link_libraries(fuzz_csp_route_work PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,Threads::Threads>" PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,csp>")
#add_fuzz_test(fuzz_csp_service_handler fuzz_csp_service_handler.cpp)
#target_link_libraries(fuzz_csp_service_handler PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,Threads::Threads>" PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,csp>")


add_fuzz_test(fuzz_test fuzz_test.cpp)
target_link_libraries(fuzz_test PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,Threads::Threads>" PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,csp>")

add_fuzz_test(fuzz_test_2 fuzz_test_2.cpp)
target_link_libraries(fuzz_test_2 PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,Threads::Threads>" PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,csp>")
add_fuzz_test(fuzz_csp_service_handler fuzz_csp_service_handler.cpp)
target_link_libraries(fuzz_csp_service_handler PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,Threads::Threads>" PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,csp>")
add_fuzz_test(fuzz_csp_route_work fuzz_csp_route_work.cpp)
target_link_libraries(fuzz_csp_route_work PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,Threads::Threads>" PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,csp>")
add_fuzz_test(fuzz_csp_get_uptime fuzz_csp_get_uptime.cpp)
target_link_libraries(fuzz_csp_get_uptime PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,Threads::Threads>" PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,csp>")
add_fuzz_test(fuzz_csp_route_work_1 fuzz_csp_route_work_1.cpp)
target_link_libraries(fuzz_csp_route_work_1 PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,Threads::Threads>" PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,csp>")
add_fuzz_test(fuzz_csp_get_buf_free_1 fuzz_csp_get_buf_free_1.cpp)
target_link_libraries(fuzz_csp_get_buf_free_1 PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,Threads::Threads>" PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,csp>")
add_fuzz_test(fuzz_csp_get_uptime_1 fuzz_csp_get_uptime_1.cpp)
target_link_libraries(fuzz_csp_get_uptime_1 PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,Threads::Threads>" PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,csp>")
add_fuzz_test(fuzz_csp_ping fuzz_csp_ping.cpp)
target_link_libraries(fuzz_csp_ping PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,Threads::Threads>" PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,csp>")
add_fuzz_test(fuzz_csp_cmp fuzz_csp_cmp.cpp)
target_link_libraries(fuzz_csp_cmp PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,Threads::Threads>" PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,csp>")
add_fuzz_test(fuzz_csp_reboot fuzz_csp_reboot.cpp)
target_link_libraries(fuzz_csp_reboot PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,Threads::Threads>" PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,csp>")
add_fuzz_test(fuzz_csp_transaction_w_opts fuzz_csp_transaction_w_opts.cpp)
target_link_libraries(fuzz_csp_transaction_w_opts PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,Threads::Threads>" PRIVATE "$<LINK_LIBRARY:WHOLE_ARCHIVE,csp>")
